export const EventList = [
	{
		image: "./images/event-carousel/enigma-logo.png",
		name: "Enigma",
		desc: "IEC's introductory event meant for freshers essentially to get the essence of 'our vision and mission'. Various innovative games including Time Capsule, where people write a note to their future selves about their goals, heads up and dumb charades of brands/entrepreneurs sum it up. It is a delightful experience with a Bollywood twist where freshers get hands-on experience about entrepreneurship.",
		modalData: {
			name: "Enigma",
			image: "./images/event-banners/enigma-banner.png",
			title: "Innovation challenge",
			data: "IEC's introductory event meant for freshers essentially to get the essence of 'our vision and mission'. Various innovative games including Time Capsule, where people write a note to their future selves about their goals, heads up and dumb charades of brands/entrepreneurs sum it up. It is a delightful experience with a Bollywood twist where freshers get hands-on experience about entrepreneurship.",
			dates: ["21st January", "31st January", "20th February"],
			rules: [
				"Lorem ipsum dolor sit amet",
				"consectetuer adipiscing elit.",
				"Aliquam tincidunt mauris eu risus.",
				"Vestibulum auctor dapibus neque.",
				"Nunc dignissim risus id metus.",
				"Cras ornare tristique elit.",
				"Vivamus vestibulum ntulla nec ante.",
				"Praesent placerat risus quis eros.",
				"Fusce pellentesque suscipit nibh.",
				"Integer vitae libero ac risus egestas placerat.",
				"Vestibulum commodo felis quis tortor.",
				"Ut aliquam sollicitudin leo.",
				"Cras iaculis ultricies nulla.",
				"Donec quis dui at dolor tempor interdum.",
			],
		},
	},
	{
		image: "./images/event-carousel/unplanned-logo.png",
		name: "Unplanned 3.0",
		desc: "Unplanned is a captivating event, in which participants have to use their prompt reasoning to create on-the-spot business plans. All participants will be presented with images based on which they have to assemble a business plan Participants will be kept on their toes as their challenges will change momentarily. his event aims to encourage improvisational skills in students while providing them with a platform to hone their planning skills.",

		modalData: {
			name: "Unplanned",
			image: "./images/event-banners/unplanned-banner.png",
			title: "Innovation challenge",
			data: "Unplanned is a captivating event, in which participants have to use their prompt reasoning to create on-the-spot business plans. All participants will be presented with images based on which they have to assemble a business plan Participants will be kept on their toes as their challenges will change momentarily. his event aims to encourage improvisational skills in students while providing them with a platform to hone their planning skills.",
			dates: ["21st January", "31st January", "20th February"],
			rules: [
				"Lorem ipsum dolor sit amet",
				"consectetuer adipiscing elit.",
				"Aliquam tincidunt mauris eu risus.",
				"Vestibulum auctor dapibus neque.",
				"Nunc dignissim risus id metus.",
				"Cras ornare tristique elit.",
				"Vivamus vestibulum ntulla nec ante.",
				"Praesent placerat risus quis eros.",
				"Fusce pellentesque suscipit nibh.",
				"Integer vitae libero ac risus egestas placerat.",
				"Vestibulum commodo felis quis tortor.",
				"Ut aliquam sollicitudin leo.",
				"Cras iaculis ultricies nulla.",
				"Donec quis dui at dolor tempor interdum.",
			],
		},
	},
	{
		image: "./images/event-carousel/inceptio-logo.png",
		name: "Inceptio 7.0",
		desc: "NMIMS MPSTME's Innovation and Entrepreneurship Carnival is an exceptional annual three-day event fostering entrepreneurship, business, and innovation. It gathers young individuals citywide to collaborate on projects, fostering discovery and teamwork.",
		modalData: {
			name: "Inceptio",
			image: "./images/event-banners/inceptio-banner.png",
			title: "Innovation challenge",
			data: "The NMIMS MPSTME's Innovation and Entrepreneurship Carnival is an exceptional annual three-day event fostering entrepreneurship, business, and innovation. It gathers young individuals citywide to collaborate on projects, fostering discovery and teamwork. The festival offers diverse experiences including workshops led by industry professionals to learn idea origination, validation, and skill application, with opportunities to win cash prizes, certificates, internships, and access to Angel Investors. Aimed at innovators and entrepreneurial spirits, it's a chance to realize potential and engage in a lifetime experience!",
			dates: ["21st January", "31st January", "20th February"],
			rules: [
				"Lorem ipsum dolor sit amet",
				"consectetuer adipiscing elit.",
				"Aliquam tincidunt mauris eu risus.",
				"Vestibulum auctor dapibus neque.",
				"Nunc dignissim risus id metus.",
				"Cras ornare tristique elit.",
				"Vivamus vestibulum ntulla nec ante.",
				"Praesent placerat risus quis eros.",
				"Fusce pellentesque suscipit nibh.",
				"Integer vitae libero ac risus egestas placerat.",
				"Vestibulum commodo felis quis tortor.",
				"Ut aliquam sollicitudin leo.",
				"Cras iaculis ultricies nulla.",
				"Donec quis dui at dolor tempor interdum.",
			],
		},
	},
	{
		image: "./images/event-carousel/concept-show-logo.png",
		name: "Concept Show",
		desc: "Description not provided yet.",
		modalData: {
			name: "Concept Show",
			image: "./images/event-banners/concept-show-banner.png",
			title: "Innovation challenge",
			data: "Description not provided yet!",
			dates: ["21st January", "31st January", "20th February"],
			rules: [
				"Lorem ipsum dolor sit amet",
				"consectetuer adipiscing elit.",
				"Aliquam tincidunt mauris eu risus.",
				"Vestibulum auctor dapibus neque.",
				"Nunc dignissim risus id metus.",
				"Cras ornare tristique elit.",
				"Vivamus vestibulum ntulla nec ante.",
				"Praesent placerat risus quis eros.",
				"Fusce pellentesque suscipit nibh.",
				"Integer vitae libero ac risus egestas placerat.",
				"Vestibulum commodo felis quis tortor.",
				"Ut aliquam sollicitudin leo.",
				"Cras iaculis ultricies nulla.",
				"Donec quis dui at dolor tempor interdum.",
			],
		},
	},
];
